spring.application.name=inscripcion-cursos
server.port=8080

# Configuracion base de datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:inscripciondb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Consola H2 accesible en /h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Logs AWS (nuevo)
logging.level.software.amazon.awssdk=DEBUG
logging.level.io.awspring.cloud=DEBUG

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/d3a7f4e6-485d-4411-9d1c-3197d9215eab/v2.0
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
#comentario para despliegue en AWS